name: flutter_architecture_example
description: A Flutter demo for using MVVM architecture and services.

version: 1.1.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.0.0
  http: ^0.13.1
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  stacked: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter:
  uses-material-design: true
